var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(_ds){var window=this;var gO=function(){return(0,_ds.V)('<input type="checkbox" class="bookmark-checkbox">')},hO=function(a){var b=a.isSignedIn;a=a.hb;let c='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-dialog"><div class="devsite-dialog-contents">';a&&(c+='<h3 class="no-link">',c=(b?c+"Create a Google Developer Profile to bookmark":c+"Sign in to bookmark")+"</h3>");c+="<p>";c=(b?a?c+"Save your frequently visited pages with a Google Developer Profile.":c+'This account is not eligible for Developer Profiles. <a href="https://web.archive.org/web/20220227165022/https://developers.google.com/profile/help#i%E2%80%99m_unable_to_create_a_profile_with_my_g_suite_account_why_is_that" target="_blank">Learn more</a>':
c+"You need to be signed in to save your frequently visited pages with a Google Developer Profile.")+"</p>";b&&a&&(c+="<p>Create your Google Developer Profile.</p>");c+='</div><div class="devsite-dialog-buttons">';c=b?a?c+'<button class="button-primary create-profile">Create profile':c+'<button class="button-primary change-account">Change account':c+'<button class="button button-primary sign-in-button">Sign in';return(0,_ds.V)(c+'</button><button class="button devsite-dialog-close">Dismiss</button></div></devsite-dialog>')},
iO=function(a){var b=a.gb;a='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-create-profile-dialog"><div class="create-profile-spinner"><devsite-spinner size="48"></devsite-spinner></div><div class="devsite-dialog-contents"><h3 class="no-link">Would you like to receive emails regarding new features, events, badges, content, and research opportunities?</h3><input type="checkbox" id="devsite-bookmark-create-profile-email-opt-in"><label for="devsite-bookmark-create-profile-email-opt-in">Yes, sign me up for Google Developer emails.</label><p class="account-note">';
b='By creating a Developer Profile, you agree to the <a href="'+(_ds.X(_ds.Y(b))+'">Content Policy</a>. Google\'s <a href="https://web.archive.org/web/20220227165022/https://policies.google.com/terms">Terms of Service</a> and <a href="https://web.archive.org/web/20220227165022/https://policies.google.com/privacy">Privacy Policy</a> apply to your use of this service. The name on your Google Account will be used in your Google Developer Profile. It may appear where you contribute and can be changed at any time.');a=a+b+'</p></div><div class="devsite-dialog-buttons"><button class="button-primary create-profile">Create Profile';
a+='</button><button class="button devsite-dialog-close">';a+="Dismiss";a+="</button></div></devsite-dialog>";return(0,_ds.V)(a)},jO=function(a){a='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-error-dialog"><div class="devsite-dialog-contents"><h3 class="no-link">Something went wrong</h3><p>'+(_ds.W(a.error)+'</p></div><div class="devsite-dialog-buttons"><button class="button devsite-dialog-close">');return(0,_ds.V)(a+"Dismiss</button></div></devsite-dialog>")};var lO=async function(a){var b=new _ds.Ai(_ds.I().href);if(_ds.Ti(b.h,"bookmark"))await kO(a),b.h.remove("bookmark"),_ds.$i(b.toString(),!0,!1);else if(await (await _ds.A()).isSignedIn()){var c=await a.W();if(null!==c&&void 0!==c&&c.profileId){b=_ds.I().href;try{b=await _ds.po(b)}catch(e){}c=(null===c||void 0===c?void 0:c.profileId)||"";var d=new _ds.hq;try{const e=await d.getPath({path:b,profileId:c});"SAVED"===(null===e||void 0===e?void 0:e.saveStatus)&&a.setAttribute("saved","")}catch(e){}}}},
mO=function(a){var b;if(a.C){var c=(a.C.checked=a.v)?"Remove bookmark":"Add bookmark";a.setAttribute("data-title",c);null===(b=a.C)||void 0===b?void 0:b.setAttribute("aria-label",c)}},nO=function(a){a.eventHandler.listen(a,"change",()=>{kO(a)})},kO=async function(a){a.toggleAttribute("saved");if(a.v){var b=await _ds.io("/saved-pages",void 0,void 0,!1,!0);oO(a,"Page saved.","View Saved Pages",b)}else oO(a,"Page unsaved.");b=await (await _ds.A()).isSignedIn();let c=!0;b&&(c=await a.hb());if(c){const d=
await a.W();if(d){await pO(a,d);return}}a.F=qO(a,b,c);a.F.setAttribute("open","")},oO=function(a,b,c,d){a.dispatchEvent(new CustomEvent("devsite-show-custom-snackbar-msg",{detail:{msg:b,linkText:c,href:null===d||void 0===d?void 0:d.href,showClose:!1},bubbles:!0}))},pO=async function(a,b){if(null===b||void 0===b||!b.profileId)return null;var c=a.v?"SAVED":"UNSAVED";let d=_ds.I().href;try{d=await _ds.po(d)}catch(g){}const e=new _ds.hq;let f=null;try{f=await e.Md({path:d,status:c,profileId:b.profileId})}catch(g){a.j=
rO(a,"There was an issue saving the page."),a.j.setAttribute("open",""),a.toggleAttribute("saved")}a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:a.v?"Saving Page to Profile":"Removing Saved Page from Profile",label:"Saving Widget"},bubbles:!0}));c=document.querySelector("devsite-user#devsite-user");b=await _ds.io("/saved-pages",null===b||void 0===b?void 0:b.profileId,null===b||void 0===b?void 0:b.vanityId,!1,!0);a.v&&!window.sessionStorage.getItem("devsite_bookmark_popout_shown")&&
(await (null===c||void 0===c?void 0:c.Rd("view-bookmarked-pages",b)),window.sessionStorage.setItem("devsite_bookmark_popout_shown","true"));return f},qO=function(a,b,c){b&&c&&sO(a,"Callout Profile intro");let d=document.body.querySelector("#devsite-bookmark-dialog");d||(d=_ds.R(hO,{isSignedIn:b,hb:c}),document.body.appendChild(d),(b=d.querySelector(".create-profile"))&&a.eventHandler.listen(b,"click",async()=>{null===d||void 0===d?void 0:d.removeAttribute("open");a.h=await tO(a);a.h.setAttribute("open",
"")}),(b=d.querySelector(".sign-in-button"))&&a.eventHandler.listen(b,"click",async e=>{e.preventDefault();e.stopPropagation();e=new _ds.Ai(_ds.I().href);e.h.add("bookmark",!0);_ds.$i(e.toString(),!0,!1);await (await _ds.A()).signIn()}),(b=d.querySelector(".change-account"))&&a.eventHandler.listen(b,"click",async e=>{e.preventDefault();e.stopPropagation();e=new _ds.Ai(_ds.I().href);e.h.add("bookmark",!0);_ds.$i(e.toString(),!0,!1);await (await _ds.A()).changeAccount()}),(b=d.querySelector(".devsite-dialog-close"))&&
a.eventHandler.listen(b,"click",()=>{a.toggleAttribute("saved");sO(a,"Callout Profile dismissed")}));return d},sO=function(a,b,c){b=Object.assign({category:"Site-Wide Custom Events",action:b,label:"Saving Widget Callout"},c||{});a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:b,bubbles:!0}))},tO=async function(a){sO(a,"Callout Profile displayed");var b=document.body.querySelector("#devsite-bookmark-create-profile-dialog");if(!b){b=(await _ds.go()).href;b=_ds.R(iO,{gb:b});document.body.appendChild(b);
var c=b.querySelector(".create-profile");c&&a.eventHandler.listen(c,"click",()=>{a.createProfile()});(c=b.querySelector(".devsite-dialog-close"))&&a.eventHandler.listen(c,"click",()=>{a.toggleAttribute("saved");sO(a,"Callout Profile dismissed")})}return b},rO=function(a,b){sO(a,"Callout Profile error",{label:"Saving Widget Callout Error"});a=document.body.querySelector("#devsite-bookmark-error-dialog");a||(a=_ds.R(jO,{error:b}),document.body.appendChild(a));return a},uO=class extends _ds.H{constructor(){super(["devsite-snackbar",
"devsite-dialog"]);this.eventHandler=new _ds.J;this.j=this.h=this.F=this.C=this.D=null;this.v=!1}static get observedAttributes(){return["saved"]}async connectedCallback(){var a,b;const c=document.body.querySelector(".devsite-page-title,.devsite-playlist-title,.devsite-quiz-title,[layout=docs] .devsite-article h1:first-of-type");c?c&&this.previousElementSibling!==c?null===(a=c.parentElement)||void 0===a?void 0:a.insertBefore(this,c.nextSibling):(this.classList.add("show"),await lO(this),_ds.Q(this,
gO),this.D=document.body.querySelector(".devsite-article"),null===(b=this.D)||void 0===b?void 0:b.setAttribute("has-bookmark",""),this.C=this.querySelector(".bookmark-checkbox"),mO(this),nO(this)):this.remove()}disconnectedCallback(){var a;_ds.K(this.eventHandler);_ds.Vh(this.F);_ds.Vh(this.h);_ds.Vh(this.j);this.C=null;null===(a=this.D)||void 0===a?void 0:a.removeAttribute("has-bookmark")}attributeChangedCallback(a,b,c){"saved"===a&&(this.v=null!==c,mO(this))}async createProfile(){var a,b,c,d,e,
f,g=await _ds.$G.getName();if(g){var h=null===(b=this.h)||void 0===b?void 0:b.querySelector("#devsite-bookmark-create-profile-email-opt-in"),k=!(!h||!h.checked);null===(c=this.h)||void 0===c?void 0:c.classList.add("loading");var l=new _ds.cx;h=null;try{await _ds.$w(l,g,k,!0),null===(d=this.h)||void 0===d?void 0:d.removeAttribute("open"),h=await this.W(),g=null,h&&(g=await pO(this,h)),sO(this,"Callout Profile created",g&&"SAVED"===g.saveStatus?{pu:"1",Tt:g.type||"UNDEFINED_TYPE"}:void 0)}catch(m){null===
(e=this.h)||void 0===e?void 0:e.removeAttribute("open"),this.j=rO(this,`${m}`),this.j.setAttribute("open",""),this.toggleAttribute("saved")}null===(f=this.h)||void 0===f?void 0:f.classList.remove("loading")}else null===(a=this.h)||void 0===a?void 0:a.removeAttribute("open"),this.j=rO(this,"There was an issue getting your account information."),this.j.setAttribute("open",""),this.toggleAttribute("saved")}async hb(){var a;if(!await (await _ds.A()).isSignedIn())return!1;const b=new _ds.Tw;let c=null;
try{c=await b.Ra()}catch(d){}return"ELIGIBILITY_ELIGIBLE"===(null===(a=null===c||void 0===c?void 0:c.createProfile)||void 0===a?void 0:a.status)}async W(){if(!await this.hb())return null;const a=new _ds.cx;let b=null;try{b=await a.W()}catch(c){}return b}};try{window.customElements.define("devsite-bookmark",uO)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookmark",a)};})(_ds_www);


}
/*
     FILE ARCHIVED ON 16:50:22 Feb 27, 2022 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 10:46:09 Mar 28, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 53.627
  exclusion.robots: 0.067
  exclusion.robots.policy: 0.058
  RedisCDXSource: 0.576
  esindex: 0.007
  LoadShardBlock: 29.66 (3)
  PetaboxLoader3.datanode: 54.184 (5)
  load_resource: 263.916 (2)
  PetaboxLoader3.resolve: 211.983
*/