var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

(function(_ds){var window=this;var tY=function(a){return(0,_ds.V)('<div class="devsite-popout" id="'+_ds.X(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},uY=function(a){let b='<button type="submit" class="button button-white devsite-search-project-scope">';a="All results in "+_ds.W(a);return(0,_ds.V)(b+a+"</button>")},vY=function(a,b,c){let d='<button type="submit" class="button button-white devsite-suggest-all-results">';b?(a="All results across "+_ds.W(c),d+=a):(a='All results for "'+
_ds.W(a)+'"',d+=a);return(0,_ds.V)(d+"</button>")},wY=function(a,b,c,d,e,f,g,h){a=(c?"":'<devsite-analytics-scope action="'+_ds.X(_ds.Y("Restricted "+d))+'">')+'<a class="devsite-result-item-link" href="'+_ds.X(_ds.Y(a))+'"><span class="devsite-suggestion-fragment">'+_ds.W(b)+"</span>"+(h?'<span class="devsite-suggestion-fragment">'+_ds.W(h)+"</span>":"")+(e?'<span class="devsite-suggestion-fragment">'+_ds.W(e)+"</span>":"")+(_ds.LC(f)&&!g?'<span class="devsite-suggestion-fragment">'+_ds.W(f)+"</span>":
"");c||(a+='<span class="devsite-result-item-confidential">Confidential</span>');return(0,_ds.V)(a+("</a>"+(c?"":"</devsite-analytics-scope>")))},xY=function(a){var b=a.projectName,c=a.ij,d=a.query,e=a.nj;a=a.jf;b='<div class="devsite-suggest-wrapper '+(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">There are no suggestions for your query</div></div>'+((e?'<div class="devsite-suggest-footer">'+(c?uY(b):"")+vY(d,c,a)+"</div>":"")+"</div>");
return(0,_ds.V)(b)},yY=function(a){var b=a.An,c=a.In,d=a.Pn,e=a.projectName,f=a.ij,g=a.query,h=a.Tn,k=a.nj;a=a.jf;let l='<div class="devsite-suggest-wrapper '+(k?"":"devsite-search-disabled")+'" tabindex="0" role="list"><div class="devsite-suggest-section">';if(0<d.length){l=l+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading" aria-level="2">Suggested searches'+((f?'<span class="devsite-suggest-project">'+
_ds.W(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');var m=d.length;for(var n=0;n<m;n++){var q=d[n];l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.X(n)+'" role="listitem" index=":'+_ds.X(n)+'">'+wY(q.getPath(),q.getTitle(),_ds.De(q,14),"Query Suggestion Click")+"</div>"}l+="</devsite-analytics-scope></div>"}l+=
0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){l=l+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading" aria-level="2">Pages'+((f?'<span class="devsite-suggest-project">'+_ds.W(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');m=b.length;for(n=0;n<m;n++)q=
b[n],l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+_ds.X(n)+'" role="listitem" index=":'+_ds.X(n)+'">'+wY(q.getPath(),q.getTitle(),_ds.De(q,14),"Page Suggestion Click",void 0,_ds.B(q,4),f)+"</div>";l+="</devsite-analytics-scope></div>"}l+=0<h.length&&0<b.length+d.length?'<hr role="none">':"";if(0<h.length){l=l+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading" aria-level="2">Reference'+
((f?'<span class="devsite-suggest-project">'+_ds.W(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');m=h.length;for(n=0;n<m;n++)q=h[n],l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.X(n)+'" role="listitem" index=":'+_ds.X(n)+'">'+wY(q.getPath(),q.getTitle(),_ds.De(q,14),"Reference Suggestion Click",_ds.B(q,3),
_ds.B(q,4),f,_ds.Be(q,10)[0])+"</div>";l+="</devsite-analytics-scope></div>"}l+=0<c.length&&0<b.length+d.length+h.length?'<hr role="none">':"";if(0<c.length){l+='<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading" aria-level="2"><span role="columnheader">Products</span></div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)h=c[d],l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.X(d)+'" role="listitem" index=":'+_ds.X(d)+'">'+wY(h.getPath(),h.getTitle(),_ds.De(h,14),"Product Suggestion Click")+"</div>";l+="</devsite-analytics-scope></div>"}l+="</div>"+(k?'<div class="devsite-suggest-footer">'+(f?uY(e):"")+vY(g,f,a)+"</div>":"")+"</div>";return(0,_ds.V)(l)};var zY=/[ .()<>{}\[\]\/:,]+/,AY=0,GY=function(a){a.h&&(a.j.listen(a.h,"suggest-service-search",b=>{a:{var c=a.C.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}BY(a,b.detail.originalEvent,!!a.H)}}),a.j.listen(a.h,"suggest-service-suggestions-received",b=>void CY(a,b)),a.j.listen(a.h,"suggest-service-focus",()=>{DY(a,"cloud-track-search-focus",null);a.K=!0;EY(a,!0)}),a.j.listen(a.h,"suggest-service-blur",()=>{EY(a,!1)}),a.j.listen(a.h,"suggest-service-input",
()=>{!a.G["Text Entered Into Search Bar"]&&a.h.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.G["Text Entered Into Search Bar"]=!0);a.K&&(DY(a,"cloud-track-search-input",null),a.K=!1)}),a.j.listen(a.h,"suggest-service-navigate",b=>void FY(a,b)),a.j.listen(document.body,"devsite-page-changed",()=>a.G={}),DevsiteApp.hasFlagAccess(168)&&a.C&&a.j.listen(a.C,
"click",b=>{b.target&&"A"===b.target.nodeName&&DY(a,"cloud-track-run-dlp",`Result: ${b.target.textContent}, Query: ${a.D.value}`)}),_ds.dE(a.h));a.v&&a.j.listen(a.v,"submit",b=>{BY(a,b)});a.C&&a.j.listen(a.C,"click",b=>{const c=b.target;var d=c.closest(".devsite-result-item-link");d&&(EY(a,!1),d=`suggestion: ${d.getAttribute("href")}`,DY(a,"cloud-track-search-submit",d));c.classList.contains("devsite-search-project-scope")&&BY(a,b,!0)});a.N&&a.j.listen(a.N,"click",()=>void EY(a,!0));a.M&&a.j.listen(a.M,
"click",()=>void EY(a,!1))},CY=function(a,b){a.J=null;b=b.detail;var c=b.suggestions;const d=b.query;if(a.h.query.toLowerCase().startsWith(d.toLowerCase()))if(c){var e=c.pc();0<e.length&&(b=e.filter(q=>q.getTitle().includes(d)),0<b.length&&(a.J=b[0].getTitle()));b=e.filter(q=>2===q.Yc());c=e.filter(q=>3===q.Yc());var f=e.filter(q=>4===q.Yc()).slice(0,5),g=e.filter(q=>1===q.Yc());e=b.length+f.length+g.length;for(var h of f)h.setPath(_ds.fj(`${a.H||"/s/results"}/?q=${h.getTitle()}`).toString());var k=
d.split(zY);c.forEach(q=>_ds.rC(q,_ds.Be(q,10).filter(r=>k.some(w=>r.includes(w)))));h=a.getAttribute("project-name")||"";var l=a.hasAttribute("project-scope"),m=a.hasAttribute("enable-search"),n=a.getAttribute("tenant-name")||"";b={An:b,projectName:h,ij:l,In:g,Pn:f,query:d,Tn:c,nj:m,jf:n};0===e?_ds.Q(a.F,xY,b):(_ds.Q(a.F,yY,b),HY(a,d));a.setAttribute("aria-expanded","true");a.F.removeAttribute("hidden")}else a.F.setAttribute("hidden",""),a.setAttribute("aria-expanded","false")},DY=function(a,b,c){a.dispatchEvent(new CustomEvent(b,
{detail:{type:"search",name:b,position:"nav",metadata:{eventDetail:c}},bubbles:!0}))},EY=function(a,b){if(a.R!==b){_ds.$D(a.h,b);if(a.R=b)a.setAttribute("search-active","");else{let c=a.C.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");a.setAttribute("aria-expanded","false");_ds.Th(a.F)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},FY=function(a,b){var c=b.detail;b=a.F.querySelector(".highlight");
let d;const e=Array.from(a.F.querySelectorAll(".devsite-result-item"));let f=[];let g,h=-1;if(b){var k=_ds.ki(b,l=>l.classList.contains("devsite-suggest-section"));f=Array.from(k.querySelectorAll(".devsite-result-item"));k=_ds.Zh(b.parentNode.parentNode);g=_ds.$h(b.parentNode.parentNode);h=e.indexOf(b)}switch(c.keyCode){case 37:if(!k&&!g)return;b&&(c=b.getAttribute("index"),g?(d=g.querySelector('[index="'+c+'"]'))||(d=_ds.Ka(Array.from(g.querySelectorAll("[index]")))):k&&((d=k.querySelector('[index="'+
c+'"]'))||(d=_ds.Ka(Array.from(k.querySelectorAll("[index]"))))));break;case 39:if(!k&&!g)return;b&&(c=b.getAttribute("index"),k?(d=k.querySelector('[index="'+c+'"]'))||(d=_ds.Ka(Array.from(k.querySelectorAll("[index]")))):g&&((d=g.querySelector('[index="'+c+'"]'))||(d=_ds.Ka(Array.from(g.querySelectorAll("[index]"))))));break;case 38:b?(d=e[h-1])||(d=_ds.Ka(f)):d=_ds.Ka(e);break;case 40:b?(d=e[h+1])||(d=f[0]):d=e[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.D.setAttribute("aria-activedescendant",
d.id),d.setAttribute("aria-selected","true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},BY=async function(a,b,c=!1){b.preventDefault();b.stopPropagation();a.hasAttribute("enable-search")&&(a.G["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.G["Full Site Search"]=!0),DevsiteApp.hasFlagAccess(168)&&DY(a,
"cloud-track-run-dlp",a.D.value),DY(a,"cloud-track-search-submit",a.J?`contains: ${a.J}`:"no match"),b=c&&a.H?_ds.fj(a.H):_ds.fj(a.v.getAttribute("action")),c=new _ds.Ai(b.href),_ds.Ni(c,"q",a.h.query),b.search=c.h.toString(),await DevsiteApp.fetchPage(b.href,!a.hasAttribute("disable-history")),EY(a,!1))},HY=function(a,b){b=new RegExp(`(${_ds.yh(b)})`,"ig");a=a.F.querySelectorAll(".devsite-suggestion-fragment");for(const c of a)a=c.innerHTML,a=a.replace(b,"<b>$1</b>"),_ds.Kc(c,_ds.Mg(a))},IY=class extends _ds.H{static get observedAttributes(){return["project-scope",
"url-scoped","disabled"]}constructor(){super();this.R=!1;this.G={};this.L="";this.H=null;this.j=new _ds.J;this.h=null;this.K=!1}disconnectedCallback(){_ds.K(this.j);this.h&&(this.h.dispose(),this.h=null)}attributeChangedCallback(a,b,c){switch(a){case "project-scope":this.L=c||"";this.h&&(this.h.M=this.L);break;case "url-scoped":this.H=c;break;case "disabled":this.D&&(this.D.disabled=null!==c)}}connectedCallback(){if(this.v=this.querySelector("form")){this.D=this.v.querySelector(".devsite-search-query");
this.N=this.v.querySelector(".devsite-search-button[search-open]");this.M=this.querySelector(".devsite-search-button[search-close]");var a=`devsite-search-popout-container-id-${++AY}`;this.D.setAttribute("aria-controls",a);this.C=_ds.R(tY,{id:a});this.F=this.C.querySelector(".devsite-suggest-results-container");this.v.appendChild(this.C);this.hasAttribute("project-scope")&&(this.L=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.H=this.getAttribute("url-scoped"));this.v&&
this.D&&(this.h=new _ds.eE(this,this.v,this.D),this.h.o=!0,this.h.V=this.hasAttribute("enable-query-completion"),this.h.K=!0,this.h.T=!0,this.h.Y=!0,this.h.M=this.L,this.h.o=this.hasAttribute("enable-suggestions"));GY(this)}}};IY.prototype.connectedCallback=IY.prototype.connectedCallback;IY.prototype.attributeChangedCallback=IY.prototype.attributeChangedCallback;IY.prototype.disconnectedCallback=IY.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",IY)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);


}
/*
     FILE ARCHIVED ON 16:21:35 Feb 27, 2022 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 10:46:11 Mar 28, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 240.694
  exclusion.robots: 0.089
  exclusion.robots.policy: 0.078
  cdx.remote: 0.069
  esindex: 0.011
  LoadShardBlock: 215.307 (3)
  PetaboxLoader3.datanode: 167.571 (5)
  load_resource: 690.733 (2)
  PetaboxLoader3.resolve: 615.957 (2)
*/